services:
  dns:
    image: lancachenet/lancache-dns:latest
    container_name: ${CONTAINER_NAME}-dns
    environment:
      - USE_GENERIC_CACHE=true
      - UPSTREAM_DNS=${DNS_IP}
    ports:
      - ${HOST_IP}:53:53/udp
      - ${HOST_IP}:53:53/tcp
    networks:
      - lancache
    restart: unless-stopped
    
  monolithic:
    image: lancachenet/monolithic:latest
    container_name: ${CONTAINER_NAME}-monolithic
    ports:
      - ${HOST_IP}:80:80/tcp
      - ${HOST_IP}:443:443/tcp
    volumes:
      - ${LANCACHE_PATH}/cache:/data/cache
      - ${LANCACHE_PATH}/logs:/data/logs
    environment:
      - CACHE_DISK_SIZE=${CACHE_SIZE}
      - MIN_FREE_DISK=${MIN_FREE_SIZE}
      - CACHE_INDEX_SIZE=${INDEX_SIZE}
      - CACHE_MAX_AGE=3650d
    networks:
      - lancache
    restart: unless-stopped
    
networks:
  lancache:
    driver: bridge
